# Generated by Django 5.1.6 on 2025-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='techstack',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Expert')], default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=50),
        ),
    ]
